version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "📦 deps: "
    groups:
      uv:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "📦 deps: "
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "📦 deps: "
    groups:
      github-actions:
        patterns:
          - "*"
